extends:
  - standard
  - prettier
env:
  es6: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - typescript
  - jest
  - prettier
rules:
  prettier/prettier: error
  typescript/no-unused-vars: error
  no-unused-vars: off
