version: '3.1'

services:
  db: 
    container_name: ramme-postgres
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: developer
      POSTGRES_DB: store
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:   
