version: '3.1'

services:
  postgres:
    container_name: postgres-rammebuddy
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rammebuddy
