version: '3.1'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://developer:secret@db:5432/store
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - .:/app/
      - /app/node_modules

  db: 
    container_name: ramme-postgres
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: developer
      POSTGRES_DB: store
      PGDATA: /tmp
    volumes: 
      - ./infra:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data